#!/bin/bash

# Choosing wallpaper
wa=$(ls ~/pix/wallhaven | shuf -n 20 | shuf -n 5 | shuf -n 1 )

# Generating color pattle and changing wallpaper
wal -qi ~/pix/wallhaven/$wa >/dev/null

# Updateing the firfox theme
pywalfox update
# notification of status
notify-send --expire-time=4 'Wallpaper Changed!!!'

# Editing the ..dwm.h file for successfull compilation of dwm 
sed -i 'N;$!P;D' $HOME/.cache/wal/colors-wal-dwm.h


#echo 'Recompiling the dwm'
cd $HOME/.config/dwm 
# auto entering the sudo passwd 
#sudo make clean install > /dev/null
echo "radio77" | sudo -S make clean install > /dev/null
#sudo make clean install > /dev/null
#wal --preview
