#!/bin/sh

picom &
wal -R &
dwmblocks &
obsidian &
inkdrop & 
#discord &
telegram-desktop & 
brave-browser &
# Running dwm in loop to avoid the restart
while true; do 
    /usr/local/bin/dwm 2> /dev/null
done
#exec dwm
